### ISSUE TITLE
flutter 在pubspec.yaml添加依赖报错

### ISSUE THREAD

**Issue by nesger** [nesger/FlutterNote#2]
Error on line 25, column 5 of pubspec.yaml: A dependency may only have one source.
    sdk: flutter
    ^^^^^^^^^^^^^

pub get failed (65)

**Comment by nesger** [comment]
这个是对齐问题
```
dev_dependencies:
  flutter_test:
    sdk: flutter

    english_words: ^3.1.0
```
这样会报错。库要跟flutter_test对齐。所以缩进一下 english_words 行就可以了。
```
dev_dependencies:
  flutter_test:
    sdk: flutter

  english_words: ^3.1.0
```
